export const DELETE_MUSIC_ELEMENT = 'DELETE_MUSIC_ELEMENT'

export const CHANGE_CARENT_MUSIC = 'CHANGE_CARENT_MUSIC'

export const SEARCH_MUSICS = 'SEARCH_MUSICS'

export const ADD_NEW_MUSIC_IN_MY_LIST = 'ADD_NEW_MUSIC_IN_MY_LIST'
