export const DELETE_MUSIC_ELEMENT = 'DELETE_MUSIC_ELEMENT'

export const CHANGE_CARENT_MUSIC = 'CHANGE_CARENT_MUSIC'

export const SEARCH_MUSICS = 'SEARCH_MUSICS'

export const ADD_NEW_MUSIC_IN_MY_LIST = 'ADD_NEW_MUSIC_IN_MY_LIST'

export const CHANGE_SELECTED_FRIEND = 'CHANGE_SELECTED_FRIEND'

export const CHANGE_FILTERS_FRIEND = 'CHANGE_FILTERS_FRIEND'

export const LOGIN_MAIN_PROFILE = 'LOGIN_MAIN_PROFILE'

export const CHANGE_CURENT_MUSIC_CATEGORY = 'CHANGE_CURENT_MUSIC_CATEGORY'

export const CHANGE_SITE_STYLE = 'CHANGE_SITE_STYLE'

export const CHANGE_PRIVATE_DATA_MAIN_PROFILE = 'CHANGE_PRIVATE_DATA_MAIN_PROFILE'
